name = "blog"
type = "javascript"
route = 'blog.lvcshu.com/*'
zone_id = 'ef036b4d9f03b8299bda12c42aec0766'
usage_model = ''
compatibility_flags = []
workers_dev = false
site = {bucket = "./public",entry-point = "workers-site"}
compatibility_date = "2022-03-22"

[build]
command = "yarn install"