# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2017

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Archives: /archives
  M & B: /movie
  About: /about
  Timeline: /timeline
  Friends: /friends
  

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>testing...</p>
widget:
  Tags: true
  Categories: false
  Custom: true

widget_custom:
    title: 友情链接
    content: <a href="https://www.ilemonrain.com/">极光星空</a><br><a href="https://ovear.info/">Ovear's Blog</a><br><a href="https://sometimesnaive.org/">南琴浪的博客</a><br><a href="https://www.xzymoe.com/">XZYMOE'S BLOG</a><br><a href="https://milkice.me">奶冰の冷藏室</a><br><a href="https://www.mengclaw.com/">萌爪实验室</a><br><a href="https://www.mrkevin.net/">Mr.KevinH</a><br><a href="https://0x.mk/">双草酸酯的博客</a><br><a href="https://www.wevg.org">Vigorous Pro</a><br><a href="https://daily.elepover.com/">Elepover's Blog</a><br><a href="https://blingwang.cn">派兹的小站</a><br><a href="https://channel.Justf.space">Justf‘s Channel</a><br><a href="https://www.swung0x48.com">Cyberspace of Swung</a><br><a href="https://blog.fsky7.com">FlyingSky's Blog</a><br><a href="https://1a23.com">1A23 Studio</a><br><a href="https://ihcr.top">翰林的小站</a>

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: false

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics: UA-122182397-1

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname: johnpoint-hexo-1


# ===========================================
# Version
# ===========================================
version: 1.1
